name: Add USC Template Entry

on:
  pull_request:
    types:
      - closed

jobs:
  process_usc_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if PR was Merged
        id: check_merged
        run: echo "::set-output name=merged::${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged }}"
        shell: bash

      - name: Copy USC Template on Merge
        if: steps.check_merged.outputs.merged == 'true'
        run: |
          # Copy the USC template to a specific directory
          cp USC_X/USC_X_template.md USC_X/usc_${{ github.run_number }}.md

      - name: Commit and Push Changes
        if: steps.check_merged.outputs.merged == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add path/to/repo_folder/usc_${{ github.run_number }}.md
          git commit -m "Add USC Template ${{ github.run_number }}"
          git push
